name: Build
on:
  push:
    branches: [master]
    tags: ['**']
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Go build
      uses: ouzi-dev/go-make-action@v1.1.0
      with:
        # Make target to run
        target: build

    - name: Go test
      uses: ouzi-dev/go-make-action@v1.1.0
      with:
        # Make target to run
        target: test
